"""Initial schema

Revision ID: 2f7432e32a1b
Revises: 
Create Date: 2026-06-24 22:34:24.866479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f7432e32a1b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('vehicle_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_plate_time'))
        batch_op.create_index(batch_op.f('ix_plate_reads_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plate_reads_track_id'), ['track_id'], unique=False)
        batch_op.create_unique_constraint('uq_camera_track_plate', ['camera_id', 'track_id', 'vehicle_number'])

    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('congestion_level',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('recorded_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_stats_time'))
        batch_op.create_index(batch_op.f('ix_traffic_stats_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_traffic_stats_id'), ['id'], unique=False)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('vehicle_number',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('violation_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('speed_kmh',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('detected_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_viol_cam'))
        batch_op.drop_index(batch_op.f('idx_viol_time'))
        batch_op.drop_index(batch_op.f('idx_viol_type'))
        batch_op.create_index(batch_op.f('ix_violations_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_violations_violation_type'), ['violation_type'], unique=False)

    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('plate',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True,
               existing_server_default=sa.text("'STOLEN'"))
        batch_op.alter_column('added_at',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.create_index(batch_op.f('ix_watchlist_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_watchlist_plate'), ['plate'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlist', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_watchlist_plate'))
        batch_op.drop_index(batch_op.f('ix_watchlist_id'))
        batch_op.alter_column('notes',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("('')"))
        batch_op.alter_column('added_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('reason',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'STOLEN'"))
        batch_op.alter_column('plate',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('violations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_violations_violation_type'))
        batch_op.drop_index(batch_op.f('ix_violations_id'))
        batch_op.drop_index(batch_op.f('ix_violations_camera_id'))
        batch_op.create_index(batch_op.f('idx_viol_type'), ['violation_type'], unique=False)
        batch_op.create_index(batch_op.f('idx_viol_time'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_viol_cam'), ['camera_id'], unique=False)
        batch_op.alter_column('detected_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('speed_kmh',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('violation_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('vehicle_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('traffic_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_traffic_stats_id'))
        batch_op.drop_index(batch_op.f('ix_traffic_stats_camera_id'))
        batch_op.create_index(batch_op.f('idx_stats_time'), ['recorded_at'], unique=False)
        batch_op.alter_column('recorded_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('congestion_level',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('plate_reads', schema=None) as batch_op:
        batch_op.drop_constraint('uq_camera_track_plate', type_='unique')
        batch_op.drop_index(batch_op.f('ix_plate_reads_track_id'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_id'))
        batch_op.drop_index(batch_op.f('ix_plate_reads_camera_id'))
        batch_op.create_index(batch_op.f('idx_plate_time'), ['detected_at'], unique=False)
        batch_op.alter_column('detected_at',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('location',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('confidence',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('vehicle_number',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('camera_id',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
